server:
  port: ${PORT:8080}

eureka:
  client:
    enabled: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: buscador
          uri: ${BUSCADOR_URL:https://buscador-production-f636.up.railway.app}
          predicates:
            - Path=/buscador/**
          filters:
            - StripPrefix=1
        - id: operador
          uri: ${OPERADOR_URL:https://operador-production.up.railway.app}
          predicates:
            - Path=/operador/**
          filters:
            - StripPrefix=1
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://power-fit-react.vercel.app}
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    org.springframework.cloud.gateway: INFO