server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: operador
          uri: ${OPERADOR_URL}
          predicates:
            - Path=/operador/**
          filters:
            - StripPrefix=1

        - id: buscador
          uri: ${BUSCADOR_URL}
          predicates:
            - Path=/buscador/**
          filters:
            - StripPrefix=1

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
