server:
  port: ${PORT:8080}
eureka:
  client:
    enabled: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: buscador
              uri: https://buscador-production-f636.up.railway.app
              predicates:
                - Path=/buscador/**
              filters:
                - StripPrefix=1
            - id: operador
              uri: https://operador-production.up.railway.app
              predicates:
                - Path=/operador/**
              filters:
                - StripPrefix=1

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
