server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: operador
          uri: ${OPERADOR_URL}
          predicates:
            - Path=/operador/**
          filters:
            - StripPrefix=1
        - id: buscador
          uri: ${BUSCADOR_URL}
          predicates:
            - Path=/buscador/**
          filters:
            - StripPrefix=1

# CORS en gateway
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
