server:
  port: ${PORT:8080}

eureka:
  client:
    enabled: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: buscador
          uri: ${BUSCADOR_URL:https://buscador-production-f636.up.railway.app}
          predicates:
            - Path=/buscador/**
          filters:
#            - StripPrefix=1
        - id: operador
          uri: ${OPERADOR_URL:https://operador-production.up.railway.app}
          predicates:
            - Path=/operador/**
          filters:
#            - StripPrefix=1
      httpclient:
        connect-timeout: 10000  # 10 segundos
        response-timeout: 30000ms  # 30 segundos
        wiretap: true

# (Opcional) Exponer endpoints para debug de rutas
management:
  endpoints:
    web:
      exposure:
        include: health,info



