server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: operador
          uri: ${OPERADOR_HOST}
          predicates:
            - Path=/operador/**
          filters:
            - StripPrefix=1
        - id: buscador
          uri: ${BUSCADOR_HOST}
          predicates:
            - Path=/buscador/**
          filters:
            - StripPrefix=1

# CORS en gateway
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
