server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: operador
          uri: ${OPERADOR_URL:http://localhost:8082}
          predicates:
            - Path=/operador/**
          filters:
            - StripPrefix=1

        - id: buscador
          uri: ${BUSCADOR_URL:http://localhost:8081}
          predicates:
            - Path=/buscador/**
          filters:
            - StripPrefix=1


management:
  endpoints:
    web:
      exposure:
        include: "health,info"
