server:
  port: ${PORT:8080}

spring:
  application:
    name: buscador

eureka:
  client:
    enabled: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  elasticsearch:
    url: https://ff181e840976497cbdace600256e7012.us-east-2.aws.elastic-cloud.com:443
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}

  operador:
    url: https://operador-production.up.railway.app/productos
  gateway:
    url: ${GATEWAY_URL}

#  ${OPERADOR_URL}


