server:
  port: ${PORT:8081}

spring:
  application:
    name: buscador

# Desactivado Eureka
eureka:
  client:
    enabled: false

elasticsearch:
  host: ${ELASTICSEARCH_HOST}   # ej: https://xxxxx.europe-west3.gcp.cloud.es.io (ejemplo)
  apiKey: ${ELASTIC_API_KEY:}   # opcional, si usas API Key

operador:
  baseUrl: ${OPERADOR_URL}      # URL pública de operador o del gateway si enrutas vía gateway
   # URL pública de operador o del gateway si enrutas vía gateway