server:
  port: ${PORT:8081}

spring:
  application:
    name: buscador

eureka:
  client:
    enabled: false

elasticsearch:
  host: ${ELASTICSEARCH_HOST:http://localhost:9200}
  user: ${ELASTICSEARCH_USER:}
  password: ${ELASTICSEARCH_PASSWORD:}

operador:
  base-url: ${OPERADOR_BASE_URL:http://localhost:8082}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
