server:
  port: ${PORT:8081}

spring:
  application:
    name: buscador

eureka:
  client:
    enabled: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  elasticsearch:
    url: ${ELASTICSEARCH_HOST}
    apiKey: ${ELASTIC_API_KEY}
  operador:
    url: ${OPERADOR_URL}
  gateway:
    url: ${GATEWAY_URL}




