server:
  port: ${PORT:8080}

spring:
  application:
    name: buscador

eureka:
  client:
    enabled: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
  elasticsearch.url: ${ELASTICSEARCH_URL}
  elasticsearch.apiKey: ${ELASTIC_API_KEY}
  operador.url: ${OPERADOR_URL}
  gateway:
    url: ${GATEWAY_URL}

