server:
  port: ${PORT:8080}

spring:
  application:
    name: buscador

eureka:
  client:
    enabled: false

app.cors.allowed-origins: ${CORS_ALLOWED_ORIGINS:https://power-fit-react-alexis-reyes.vercel.app}

elasticsearch:
  url: ${ELASTICSEARCH_URL}
  apiKey: ${ELASTIC_API_KEY}

operador.url: ${OPERADOR_URL:https://operador-production.up.railway.app/productos}
gateway.url: ${GATEWAY_URL}
