server:
  port: 8081

spring:
  application:
    name: buscador

# Desactivado Eureka
eureka:
  client:
    enabled: false

# Host de Elasticsearch viene por env var
elasticsearch:
  host: ${ELASTICSEARCH_HOST:http://localhost:9200}

# (opcional) CORS si expones endpoints directos
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
