server:
  port: ${PORT:8082}

spring:
  application:
    name: operador

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    enabled: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
