spring:
  jpa:
    hibernate:
      # En producción puedes mantener update mientras iteras; luego cambiar a validate
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

# Puedes sobreescribir aquí cualquier otro ajuste específico de prod.